services:
    postgres:
        image: postgres:latest
        container_name: 'postgres'
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=my_db
        ports:
            - '5432:5432'
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        networks:
          - my-pg-network
networks:
  my-pg-network:
    driver: bridge