---
- name: Build nginx
  hosts: main
  become: true
  tasks: 
    - name: Поднимаем nginx
      block:
        - name: Создаем директорию статики nginx
          file:
            path: ./nginx/static
            state: directory
            mode: "0755"

        - name: "Создаем конфиг nginx"
          copy:
            dest: ./nginx/config.conf
            content: "{{nginx_config}}"
            mode: "0644"

        - name: "Добавляем статику nginx"
          copy:
            dest: ./nginx/static/index.html
            content: "{{nginx_index}}"
            mode: "0644"

        - name: Поднимаем docker контейнер nginx 
          community.docker.docker_container:
            name: nginx
            image: nginx:latest
            state: started
            ports:
              - "8081:80"
            volumes:
              - "./nginx/static:/usr/share/nginx/html"
              - "./nginx/config.conf:/etc/nginx/conf.d/default.conf"